### ISSUE TITLE
can't seem to figure out how to send orders

### ISSUE THREAD

**Issue by dthread** [quickfixgo/examples#1]
I've been able to logon with the client, but can't figure out the structure yet to send orders.

Two minor changes I spotted that needed fixing:
func (e TradeClient) FromApp(msg quickfix.Message, sessionID quickfix.SessionID) (reject quickfix.MessageRejectError) {
	fmt.Println("FromApp: ", msg.String()) //This message is in a FIX Message object. not printable directly yet
	return
}

and

func (s logonState) FixMsgIn(session *Session, msg Message) (nextState sessionState) {
	msgType := new(fix.StringValue)
	if err := msg.Header.GetField(tag.MsgType, msgType); err == nil && msgType.Value == "A" {
		if err := session.handleLogon(msg); err != nil {
			session.log.OnEvent(err.Error())
			return latentState{}
		}

		return inSession{}
	}

	session.log.OnEventf("Invalid Session State: Received Msg %v while waiting for Logon", msg.String())
	return latentState{}
}

thanks

**Comment by cbusbey** [comment]
Should work with latest codebase now
