### ISSUE TITLE
Message.Build seems are removed from latest repo

### ISSUE THREAD

**Issue by TangMonk** [quickfixgo/examples#10]
https://github.com/quickfixgo/examples/blob/8f1107410a0bf70c9c89ed769de2eb0ad4577c26/cmd/tradeclient/tradeclient.go#L44

**Comment by cbusbey** [comment]
Yes, the examples had been vendoring an older version of quickfix.  We've just updated the examples to work with the current quickfix tip packages.

**Comment by TangMonk** [comment]
thanks!
